// Chain capability registry — the single seam the multichain UI reads
// (shiro's interface contract, msg 23063; kami's acceptance contract, 23060/23065,
// re-audit blockers 23086).
//
// Readiness is DERIVED from the script-generated evidence artifact
// (chainEvidence.ts — real poolIds, quotes, blocks, gateway bytecode facts),
// never from hand-set booleans. Fail-closed at every step:
//   status 'live' ⇐ complete verified config
//     AND a proven execution path (configured gateway whose deployed bytecode
//         has the executeSwap selector and embeds the chain's UniversalRouter —
//         Permit2 binding is the ROUTER's property, proven by chainverify.mjs)
//     AND ≥1 PROVEN market (exact V4 PoolKey + live liquidity + real quote)
//     AND read-smoke evidence
//     AND trade-smoke evidence (a real end-to-end trade — no chain has this yet).
// Anything less renders 'coming'. The live app's NETWORKS array (Robinhood-only)
// is untouched; the switcher migrates to this registry as chains genuinely light up.

import type { NetworkConfig, V4Contracts } from "./constants";
import {
  V4_CONTRACTS_BY_CHAIN,
  isGatewayLive,
  ROBINHOOD_MAINNET,
  OPTIMISM_MAINNET,
  INK_MAINNET,
  UNICHAIN_MAINNET,
  ETHEREUM_MAINNET,
  BNB_MAINNET,
  XLAYER_MAINNET,
} from "./constants";
import { CHAIN_EVIDENCE, type ChainEvidence, type MarketEvidence } from "./chainEvidence";
import { evidencePoolIdMatches } from "./v4Encoding";

export type ChainStatus = "live" | "coming" | "unsupported";
export type ChainRole = "launch+trade" | "trade";

export interface ChainCapability {
  id: number;
  name: string;
  shortName: string;
  /** Chain icon asset path (/public/chains/*.svg — all 7 shipped). */
  logo?: string;
  nativeSymbol: string;
  explorer: string;
  status: ChainStatus;
  role: ChainRole;
  browse: {
    kind: "hyde-launches" | "curated-markets";
    /** Proven markets only (exact PoolKey + liquidity + quote evidence) — the
     *  curated-markets browse source. Raw token lists are selector metadata,
     *  never a market claim (kami blocker #3). */
    markets: MarketEvidence[];
  };
  /** Full config references, not a shadow subset (kami blocker #4). Null until
   *  the chain's execution path + config completeness are proven. */
  trade: {
    network: NetworkConfig;
    contracts: V4Contracts;
  } | null;
  smoke: { read: boolean; trade: boolean };
  /** The evidence this derivation used — auditable, regenerated by scripts. */
  evidence?: ChainEvidence;
}

/** The 7 clint-locked chains (msg 23047/23064): Robinhood = launch+trade, the
 *  rest = curated-markets trade venues. Order = kami's rollout waves. */
// logo paths = the 7 shipped assets in /public/chains (kami 23091 cleanup).
const CANDIDATES: Array<{ net: NetworkConfig; shortName: string; role: ChainRole; logo: string }> = [
  { net: ROBINHOOD_MAINNET, shortName: "RH", role: "launch+trade", logo: "/chains/rh.svg" },
  { net: OPTIMISM_MAINNET, shortName: "OP", role: "trade", logo: "/chains/op.svg" },
  { net: INK_MAINNET, shortName: "INK", role: "trade", logo: "/chains/ink.svg" },
  { net: UNICHAIN_MAINNET, shortName: "UNI", role: "trade", logo: "/chains/uni.svg" },
  { net: BNB_MAINNET, shortName: "BNB", role: "trade", logo: "/chains/bnb.svg" },
  { net: XLAYER_MAINNET, shortName: "OKX", role: "trade", logo: "/chains/okx.svg" },
  { net: ETHEREUM_MAINNET, shortName: "ETH", role: "trade", logo: "/chains/eth.svg" },
];

const ZERO = "0x0000000000000000000000000000000000000000";
/** Placeholder addresses in constants.ts are short mnemonic hex (beef/cafe/f00d/…)
 *  left-padded with zeros — every REAL address has a non-zero high half. This
 *  predicate is the fail-closed test: unknown/zero/placeholder ⇒ not real. */
function isRealAddress(addr?: string): boolean {
  if (!addr || addr === ZERO) return false;
  return !/^0x0{20,}/i.test(addr);
}

/** Execution path is PROVEN, not configured: the configured gateway address must
 *  match the evidence entry, whose deployed-bytecode facts (executeSwap selector
 *  + embedded UniversalRouter immutable) came from a live getCode probe. */
function executionPathProven(net: NetworkConfig, v4: V4Contracts | undefined, ev: ChainEvidence | undefined): boolean {
  if (!v4 || !isGatewayLive(net.id)) return false;
  const gw = ev?.gateway;
  if (!gw) return false;
  return (
    gw.address.toLowerCase() === v4.gateway.toLowerCase() &&
    gw.codeBytes > 0 &&
    gw.hasExecuteSwapSelector &&
    gw.embedsUniversalRouter
  );
}

function deriveCapability(net: NetworkConfig, shortName: string, role: ChainRole, logo: string): ChainCapability {
  const v4 = V4_CONTRACTS_BY_CHAIN[net.id];
  const ev = CHAIN_EVIDENCE[net.id];

  const configComplete =
    !!v4 &&
    isRealAddress(v4.poolManager) &&
    isRealAddress(v4.universalRouter) &&
    isRealAddress(v4.quoter) &&
    isRealAddress(v4.permit2) &&
    isRealAddress(v4.stateView) &&
    isRealAddress(net.weth) &&
    net.rpcUrl.length > 0 &&
    net.explorerUrl.length > 0 &&
    net.tokens.length > 0;

  // A market is only exposed if the APP'S OWN encoder reproduces its proven
  // poolId (kami 23091: evidence PoolKey ↔ encoded PoolKey regression). An
  // unreproducible market means encoder drift — excluded, loudly.
  const markets = (ev?.markets ?? []).filter((m) => {
    const ok = evidencePoolIdMatches(m);
    if (!ok) console.error(`[chainRegistry] market ${m.symbol} on ${net.name}: evidence poolId not reproducible by app encoder — EXCLUDED`);
    return ok;
  });
  const smoke = {
    read: !!ev?.readSmoke && ev.chainId === net.id,
    trade: !!ev?.tradeSmoke && ev.chainId === net.id,
  };

  const tradeReady = configComplete && executionPathProven(net, v4, ev);
  const marketsReady = role === "launch+trade" ? true : markets.length > 0;

  const status: ChainStatus =
    tradeReady && marketsReady && smoke.read && smoke.trade ? "live" : "coming";

  return {
    id: net.id,
    name: net.name,
    shortName,
    logo,
    nativeSymbol: net.currencySymbol,
    explorer: net.explorerUrl,
    status,
    role,
    browse:
      role === "launch+trade"
        ? { kind: "hyde-launches", markets: [] }
        : { kind: "curated-markets", markets },
    trade: tradeReady && v4 ? { network: net, contracts: v4 } : null,
    smoke,
    evidence: ev,
  };
}

/** Every candidate chain with its derived (fail-closed) capability. */
export function chainCapabilities(): ChainCapability[] {
  return CANDIDATES.map(({ net, shortName, role, logo }) => deriveCapability(net, shortName, role, logo));
}

/** Registry lookup; chains outside the locked 7 are honestly 'unsupported'. */
export function chainCapability(chainId: number): ChainCapability | { id: number; status: "unsupported" } {
  const hit = chainCapabilities().find((c) => c.id === chainId);
  return hit ?? { id: chainId, status: "unsupported" };
}
