// AUTO-GENERATED by scripts/chainevidence-v3.mjs — DO NOT HAND-EDIT.
// Regenerate: node scripts/chainevidence-v3.mjs
// The V3 registry (chainRegistry.ts) derives readiness from THIS artifact's raw facts (addresses, tick
// spacing, code hashes, block) by deriving equality vs the configured row — never trusting summary
// booleans. `launch` (Hyde launchpad) and `trade` (swap) proofs stay null until gojo signs them, so a
// chain is fail-closed 'coming' (launch/Swap disabled) until real deployment + round-trip evidence.

export interface V3InfraEvidence {
  chainId: number;
  numeraire: { address: string; decimals: number; symbol: string };
  factory: { address: string; feeTier: number; tickSpacing: number; codeHash: string; codeSize: number };
  positionManager: { address: string; factoryBinding: string; codeHash: string; codeSize: number };
  numeraireCode: { codeHash: string; codeSize: number };
  verifiedAtBlock: string;
}
/** Hyde's OWN deployed launchpad — the LAUNCH-enabled gate (gojo signs after deploy + round-trip). */
export interface V3LaunchEvidence {
  pad: string;
  locker: string;
  padCodeSize: number;
  lockerCodeSize: number;
  padLockerBinding?: string;   // pad.LOCKER() (== locker) — gojo sign-off
  lockerFactoryBinding?: string; // locker.FACTORY() (== pad) — gojo sign-off
  deployTx?: string;
  launchRoundTripFdv?: string; // ~$5k slot0.tick round-trip — gojo sign-off
  verifiedAtBlock?: string;
}
/** Independent swap path — gojo signs after SwapRouter02 + QuoterV2 verify + funded smoke. */
export interface V3TradeEvidence {
  swapRouter: string;
  quoter: string;
  quoteSmoke: { amountIn: string; amountOut: string; atBlock: string };
  tradeSmoke: { txHash: string; atBlock: string };
}
export interface V3ChainEvidence {
  chainId: number;
  generatedAtBlock: string;
  rpcUrl?: string;
  infra?: V3InfraEvidence;
  launch?: V3LaunchEvidence | null;
  trade?: V3TradeEvidence | null;
  readSmoke?: { verifiedAtBlock: string } | null;
}

export const CHAIN_EVIDENCE_V3: Record<number, V3ChainEvidence | undefined> = {
  "988": {
    "chainId": 988,
    "generatedAtBlock": "32879997",
    "rpcUrl": "https://rpc.stable.xyz",
    "infra": {
      "chainId": 988,
      "numeraire": {
        "address": "0x779Ded0c9e1022225f8E0630b35a9b54bE713736",
        "decimals": 6,
        "symbol": "USDT0"
      },
      "factory": {
        "address": "0x88F0a512eF09175D456bc9547f914f48C013E4aA",
        "feeTier": 10000,
        "tickSpacing": 200,
        "codeHash": "0x2616b5c05e19fc8931cdf2f08bf47e05a7db6859c23add2c32d226092409e939",
        "codeSize": 24535
      },
      "positionManager": {
        "address": "0x3BdC3437405f7D801b6036532713fc1F179136a6",
        "factoryBinding": "0x88F0a512eF09175D456bc9547f914f48C013E4aA",
        "codeHash": "0x553e7df57c6a17f6d65f05f5c3a3fa41ddaebeca6cf90a0b2b59da3152c41371",
        "codeSize": 24384
      },
      "numeraireCode": {
        "codeHash": "0x4d9be648c5bf39973670d9f8b481d5d0b971e6a2db2deccc6b98cde21c5dd83e",
        "codeSize": 2227
      },
      "verifiedAtBlock": "32879997"
    },
    "launch": null,
    "trade": null,
    "readSmoke": null
  }
};
