// AUTO-GENERATED by scripts/chainevidence.mjs — DO NOT HAND-EDIT.
// Regenerate: node scripts/chainevidence.mjs   ·   Re-prove: node scripts/chainverify.mjs
// The registry (chainRegistry.ts) derives chain readiness from THIS artifact's
// verifiable contents (blocks, poolIds, quotes) — hand-edits are overwritten by
// the next run and carry no authority. tradeSmoke entries can only be written
// by a real funded end-to-end trade run (separate script, not yet built).

export type GatewayEvidence = {
  address: `0x${string}`;
  codeBytes: number;
  hasExecuteSwapSelector: boolean;
  embedsUniversalRouter: boolean;
  embedsPermit2: boolean;
  verifiedAtBlock: string;
};
export type MarketEvidence = {
  token: `0x${string}`;
  symbol: string;
  decimals: number;
  poolKey: { currency0: `0x${string}`; currency1: `0x${string}`; fee: number; tickSpacing: number; hooks: `0x${string}` };
  poolId: `0x${string}`;
  liquidity: string;
  sqrtPriceX96: string;
  quote: { amountIn: string; amountOut: string; zeroForOne: boolean; atBlock: string };
};
export type ReadSmokeEvidence = { poolId: `0x${string}`; sqrtPriceX96: string; verifiedAtBlock: string };
export type TradeSmokeEvidence = { txHash: `0x${string}`; atBlock: string };
export type ChainEvidence = {
  chainId: number;
  generatedAtBlock: string;
  gateway?: GatewayEvidence;
  markets: MarketEvidence[];
  readSmoke?: ReadSmokeEvidence;
  tradeSmoke?: TradeSmokeEvidence;
};

export const CHAIN_EVIDENCE: Record<number, ChainEvidence> = {
  "10": {
    "chainId": 10,
    "generatedAtBlock": "154473043",
    "markets": [
      {
        "token": "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85" as `0x${string}`,
        "symbol": "USDC",
        "decimals": 6,
        "poolKey": {
          "currency0": "0x0000000000000000000000000000000000000000" as `0x${string}`,
          "currency1": "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85" as `0x${string}`,
          "fee": 500,
          "tickSpacing": 10,
          "hooks": "0x0000000000000000000000000000000000000000" as `0x${string}`
        },
        "poolId": "0x51bf4cc5b8d9f7f759e41f572fe2a25bc2aeb42432bf12544a350595e5c8bb43" as `0x${string}`,
        "liquidity": "57205278151019019",
        "sqrtPriceX96": "3424093889111155110723191",
        "quote": {
          "amountIn": "1000000000000000",
          "amountOut": "1866872",
          "zeroForOne": true,
          "atBlock": "154473043"
        }
      },
      {
        "token": "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58" as `0x${string}`,
        "symbol": "USDT",
        "decimals": 6,
        "poolKey": {
          "currency0": "0x0000000000000000000000000000000000000000" as `0x${string}`,
          "currency1": "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58" as `0x${string}`,
          "fee": 500,
          "tickSpacing": 10,
          "hooks": "0x0000000000000000000000000000000000000000" as `0x${string}`
        },
        "poolId": "0xc68a16ae9f4ef1f071d2e14e76d50990728c14f2ea46e28c995a173735068310" as `0x${string}`,
        "liquidity": "1485693970554591",
        "sqrtPriceX96": "3425193671884220181158696",
        "quote": {
          "amountIn": "1000000000000000",
          "amountOut": "1868018",
          "zeroForOne": true,
          "atBlock": "154473043"
        }
      },
      {
        "token": "0x4200000000000000000000000000000000000042" as `0x${string}`,
        "symbol": "OP",
        "decimals": 18,
        "poolKey": {
          "currency0": "0x0000000000000000000000000000000000000000" as `0x${string}`,
          "currency1": "0x4200000000000000000000000000000000000042" as `0x${string}`,
          "fee": 3000,
          "tickSpacing": 60,
          "hooks": "0x0000000000000000000000000000000000000000" as `0x${string}`
        },
        "poolId": "0x5c204f3724cc4dbe95cb53c9a968ae3eee46c3b4092d500770dc9c2a3f44d88b" as `0x${string}`,
        "liquidity": "332603864149817354278",
        "sqrtPriceX96": "11211834915371969529831353267381",
        "quote": {
          "amountIn": "1000000000000000",
          "amountOut": "19957456605119745183",
          "zeroForOne": true,
          "atBlock": "154473043"
        }
      },
      {
        "token": "0x68f180fcCe6836688e9084f035309E29Bf0A2095" as `0x${string}`,
        "symbol": "WBTC",
        "decimals": 8,
        "poolKey": {
          "currency0": "0x0000000000000000000000000000000000000000" as `0x${string}`,
          "currency1": "0x68f180fcCe6836688e9084f035309E29Bf0A2095" as `0x${string}`,
          "fee": 3000,
          "tickSpacing": 60,
          "hooks": "0x0000000000000000000000000000000000000000" as `0x${string}`
        },
        "poolId": "0x5876423ef0d34b53e8ca5d6972ff9a9d72261eacf645a2fad664450f3eebc003" as `0x${string}`,
        "liquidity": "545276387173054",
        "sqrtPriceX96": "135056825171383835951608",
        "quote": {
          "amountIn": "1000000000000000",
          "amountOut": "2897",
          "zeroForOne": true,
          "atBlock": "154473043"
        }
      }
    ],
    "gateway": {
      "address": "0x21d6Ce25aa1AB3F59eE51b7693A596C6d39A03C9" as `0x${string}`,
      "codeBytes": 1497,
      "hasExecuteSwapSelector": true,
      "embedsUniversalRouter": true,
      "embedsPermit2": false,
      "verifiedAtBlock": "154473043"
    },
    "readSmoke": {
      "poolId": "0x5c204f3724cc4dbe95cb53c9a968ae3eee46c3b4092d500770dc9c2a3f44d88b" as `0x${string}`,
      "sqrtPriceX96": "11211834915371969529831353267381",
      "verifiedAtBlock": "154473043"
    }
  },
  "130": {
    "chainId": 130,
    "generatedAtBlock": "53796526",
    "markets": [
      {
        "token": "0x078D782b760474a361dDA0AF3839290b0EF57AD6" as `0x${string}`,
        "symbol": "USDC",
        "decimals": 6,
        "poolKey": {
          "currency0": "0x0000000000000000000000000000000000000000" as `0x${string}`,
          "currency1": "0x078D782b760474a361dDA0AF3839290b0EF57AD6" as `0x${string}`,
          "fee": 500,
          "tickSpacing": 10,
          "hooks": "0x0000000000000000000000000000000000000000" as `0x${string}`
        },
        "poolId": "0x3258f413c7a88cda2fa8709a589d221a80f6574f63df5a5b6774485d8acc39d9" as `0x${string}`,
        "liquidity": "65260216829208665",
        "sqrtPriceX96": "3424172238919790269300736",
        "quote": {
          "amountIn": "1000000000000000",
          "amountOut": "1866957",
          "zeroForOne": true,
          "atBlock": "53796526"
        }
      },
      {
        "token": "0x9151434b16b9763660705744891fA906F660EcC5" as `0x${string}`,
        "symbol": "USD₮0",
        "decimals": 6,
        "poolKey": {
          "currency0": "0x0000000000000000000000000000000000000000" as `0x${string}`,
          "currency1": "0x9151434b16b9763660705744891fA906F660EcC5" as `0x${string}`,
          "fee": 500,
          "tickSpacing": 10,
          "hooks": "0x0000000000000000000000000000000000000000" as `0x${string}`
        },
        "poolId": "0x04b7dd024db64cfbe325191c818266e4776918cd9eaf021c26949a859e654b16" as `0x${string}`,
        "liquidity": "16188159461766984",
        "sqrtPriceX96": "3425791314919577274461932",
        "quote": {
          "amountIn": "1000000000000000",
          "amountOut": "1868720",
          "zeroForOne": true,
          "atBlock": "53796526"
        }
      }
    ],
    "readSmoke": {
      "poolId": "0x3258f413c7a88cda2fa8709a589d221a80f6574f63df5a5b6774485d8acc39d9" as `0x${string}`,
      "sqrtPriceX96": "3424172238919790269300736",
      "verifiedAtBlock": "53796526"
    }
  },
  "57073": {
    "chainId": 57073,
    "generatedAtBlock": "51046471",
    "markets": [],
    "gateway": {
      "address": "0x21d6Ce25aa1AB3F59eE51b7693A596C6d39A03C9" as `0x${string}`,
      "codeBytes": 1946,
      "hasExecuteSwapSelector": true,
      "embedsUniversalRouter": true,
      "embedsPermit2": false,
      "verifiedAtBlock": "51046471"
    }
  }
} as const;
