// Chain capability registry — the single seam the multichain UI reads
// (shiro's interface contract, msg 23063; kami's acceptance contract, 23060/23065,
// re-audit blockers 23086).
//
// Readiness is DERIVED from the script-generated evidence artifact
// (chainEvidence.ts — real poolIds, quotes, blocks, gateway bytecode facts),
// never from hand-set booleans. Fail-closed at every step:
//   status 'live' ⇐ complete verified config
//     AND a proven execution path (configured gateway whose deployed bytecode
//         has the executeSwap selector and embeds the chain's UniversalRouter —
//         Permit2 binding is the ROUTER's property, proven by chainverify.mjs)
//     AND ≥1 PROVEN market (exact V4 PoolKey + live liquidity + real quote)
//     AND read-smoke evidence
//     AND trade-smoke evidence (a real end-to-end trade — no chain has this yet).
// Anything less renders 'coming'. The live app's NETWORKS array (Robinhood-only)
// is untouched; the switcher migrates to this registry as chains genuinely light up.

import type { NetworkConfig, V4Contracts } from "./constants";
import {
  V4_CONTRACTS_BY_CHAIN,
  isGatewayLive,
  ROBINHOOD_MAINNET,
  OPTIMISM_MAINNET,
  INK_MAINNET,
  UNICHAIN_MAINNET,
  ETHEREUM_MAINNET,
  BNB_MAINNET,
  XLAYER_MAINNET,
  ARBITRUM_MAINNET,
} from "./constants";
import { CHAIN_EVIDENCE, type ChainEvidence, type MarketEvidence } from "./chainEvidence";
import { CHAIN_EVIDENCE_V3, type V3ChainEvidence } from "./chainEvidenceV3";
import { evidencePoolIdMatches } from "./v4Encoding";

export type ChainStatus = "live" | "coming" | "unsupported";
/** "launch" = launch-only. "launch+trade" = launch plus a verified in-app execution path.
 *  "trade" = a trade venue without Hyde launch deployment. */
export type ChainRole = "launch+trade" | "trade" | "launch";

/** Which launch/trade stack a chain runs: V4 hooks (premium line, WETH numeraire) or single-sided
 *  V3 (reach line, USDT0/stable numeraire). The data layer branches on this; components never do
 *  (shiro V3_MULTICHAIN_UI_DESIGN §1). */
export type LaunchEngine = "v4-hook" | "v3-single-sided";

/** The launch/pricing asset for a chain. Every field is a CONFIG literal — never read on-chain
 *  (Stable's USDT0 reverts on symbol()/decimals(); §2 of CONTRACT_SPEC_V3_LINE). */
export interface NumeraireInfo {
  address: string;
  /** Display only — never an on-chain symbol() call. */
  symbol: string;
  /** Config literal; drives raw↔human scaling. USDT0 = 6, WETH = 18. */
  decimals: number;
  /** Price-render precision (see formatPrice/formatFdv). */
  displayDecimals: number;
  /** USDT0/USDC → render "$"; WETH → render the symbol / native glyph. */
  usdPegged: boolean;
}

export interface ChainCapability {
  id: number;
  name: string;
  shortName: string;
  /** Chain icon asset path (/public/chains/*.svg — all 7 shipped). */
  logo?: string;
  nativeSymbol: string;
  explorer: string;
  status: ChainStatus;
  role: ChainRole;
  /** Which stack this chain launches/trades on. The DATA layer branches on this; components read
   *  engine-specific copy via ENGINE_META so V4 copy can never leak onto a V3 chain (kami 24242). */
  engine: LaunchEngine;
  /** The launch/pricing asset for this chain — config literals, never on-chain reads. */
  numeraire: NumeraireInfo;
  browse: {
    kind: "hyde-launches" | "curated-markets";
    /** Proven markets only (exact PoolKey + liquidity + quote evidence) — the
     *  curated-markets browse source. Raw token lists are selector metadata,
     *  never a market claim (kami blocker #3). */
    markets: MarketEvidence[];
  };
  /** Engine-discriminated trade/launch config (kami 24254 #2). Null until the chain's execution path +
   *  config completeness are proven. For V3, non-null REQUIRES Hyde's own V3 launchpad deployed — canonical
   *  Uniswap V3 existing is not enough to be app-available. */
  trade: TradeConfig | null;
  smoke: { read: boolean; trade: boolean };
  /** The evidence this derivation used — auditable, regenerated by scripts. V4 (ChainEvidence) or V3
   *  (V3ChainEvidence); the V3 branch no longer discards it (kami 24254 #4). */
  evidence?: ChainEvidence | V3ChainEvidence;
}

/** In-app SWAP execution config, engine-tagged. `trade === null` means the execution path remains
 *  fail-closed; non-null means the router/quoter and funded smoke evidence passed for that engine. */
export type TradeConfig =
  | { engine: "v4-hook"; network: NetworkConfig; contracts: V4Contracts }
  | {
      engine: "v3-single-sided";
      swapRouter: string;
      quoter: string;
      feeTier: number;
      numeraire: NumeraireInfo;
    };

/** Registry candidates. A selectable chain can remain fail-closed "coming":
 * canonical DEX infrastructure alone never implies a live Hydeout launcher. */
const CANDIDATES: Array<{ net: NetworkConfig; shortName: string; role: ChainRole; logo: string }> = [
  { net: ROBINHOOD_MAINNET, shortName: "RH", role: "launch+trade", logo: "/chains/rh.svg" },
  { net: ARBITRUM_MAINNET, shortName: "ARB", role: "launch+trade", logo: "/chains/arb.svg" },
  { net: OPTIMISM_MAINNET, shortName: "OP", role: "trade", logo: "/chains/op.svg" },
  { net: INK_MAINNET, shortName: "INK", role: "trade", logo: "/chains/ink.svg" },
  { net: UNICHAIN_MAINNET, shortName: "UNI", role: "trade", logo: "/chains/uni.svg" },
  { net: BNB_MAINNET, shortName: "BNB", role: "trade", logo: "/chains/bnb.svg" },
  { net: XLAYER_MAINNET, shortName: "OKX", role: "trade", logo: "/chains/okx.svg" },
  { net: ETHEREUM_MAINNET, shortName: "ETH", role: "trade", logo: "/chains/eth.svg" },
];

const ZERO = "0x0000000000000000000000000000000000000000";
/** Placeholder addresses in constants.ts are short mnemonic hex (beef/cafe/f00d/…)
 *  left-padded with zeros — every REAL address has a non-zero high half. This
 *  predicate is the fail-closed test: unknown/zero/placeholder ⇒ not real. */
function isRealAddress(addr?: string): boolean {
  if (!addr || addr === ZERO) return false;
  return !/^0x0{20,}/i.test(addr);
}
/** A real 32-byte tx hash (deploy/trade provenance) — not zero, correct width. */
function isRealTxHash(h?: string): boolean {
  return !!h && /^0x[0-9a-fA-F]{64}$/.test(h) && !/^0x0{64}$/.test(h);
}

/** Execution path is PROVEN, not configured: the configured gateway address must
 *  match the evidence entry, whose deployed-bytecode facts (executeSwap selector
 *  + embedded UniversalRouter immutable) came from a live getCode probe. */
function executionPathProven(net: NetworkConfig, v4: V4Contracts | undefined, ev: ChainEvidence | undefined): boolean {
  if (!v4 || !isGatewayLive(net.id)) return false;
  const gw = ev?.gateway;
  if (!gw) return false;
  return (
    gw.address.toLowerCase() === v4.gateway.toLowerCase() &&
    gw.codeBytes > 0 &&
    gw.hasExecuteSwapSelector &&
    gw.embedsUniversalRouter
  );
}

function deriveCapability(net: NetworkConfig, shortName: string, role: ChainRole, logo: string): ChainCapability {
  const v4 = V4_CONTRACTS_BY_CHAIN[net.id];
  const ev = CHAIN_EVIDENCE[net.id];

  const configComplete =
    !!v4 &&
    isRealAddress(v4.poolManager) &&
    isRealAddress(v4.universalRouter) &&
    isRealAddress(v4.quoter) &&
    isRealAddress(v4.permit2) &&
    isRealAddress(v4.stateView) &&
    isRealAddress(net.weth) &&
    net.rpcUrl.length > 0 &&
    net.explorerUrl.length > 0 &&
    net.tokens.length > 0;

  // A market is only exposed if the APP'S OWN encoder reproduces its proven
  // poolId (kami 23091: evidence PoolKey ↔ encoded PoolKey regression). An
  // unreproducible market means encoder drift — excluded, loudly.
  const markets = (ev?.markets ?? []).filter((m) => {
    const ok = evidencePoolIdMatches(m);
    if (!ok) console.error(`[chainRegistry] market ${m.symbol} on ${net.name}: evidence poolId not reproducible by app encoder — EXCLUDED`);
    return ok;
  });
  const smoke = {
    read: !!ev?.readSmoke && ev.chainId === net.id,
    trade: !!ev?.tradeSmoke && ev.chainId === net.id,
  };

  const tradeReady = configComplete && executionPathProven(net, v4, ev);
  const marketsReady = role === "launch+trade" ? true : markets.length > 0;

  const status: ChainStatus =
    tradeReady && marketsReady && smoke.read && smoke.trade ? "live" : "coming";

  return {
    id: net.id,
    name: net.name,
    shortName,
    logo,
    nativeSymbol: net.currencySymbol,
    explorer: net.explorerUrl,
    status,
    role,
    engine: "v4-hook",
    // The V4 line prices in WETH (18-dec, native — not USD-pegged).
    numeraire: { address: net.weth, symbol: "WETH", decimals: 18, displayDecimals: 8, usdPegged: false },
    browse:
      role === "launch+trade"
        ? { kind: "hyde-launches", markets: [] }
        : { kind: "curated-markets", markets },
    trade: tradeReady && v4 ? { engine: "v4-hook", network: net, contracts: v4 } : null,
    smoke,
    evidence: ev,
  };
}

// ---------------------------------------------------------------- V3 line --
// The V3 "reach line": single-sided, permanently-locked launches on chains that have canonical Uniswap V3
// but NOT V4 (CONTRACT_SPEC_V3_LINE §0; shiro V3_MULTICHAIN_UI_DESIGN §2). Same fail-closed rule as V4: a
// row only goes 'live' when gojo's V3 chainverify evidence proves the execution path — else 'coming'.

export interface V3ChainRow {
  id: number;
  name: string;
  shortName: string;
  logo?: string;
  rpcUrl: string;
  explorer: string;
  nativeSymbol: string;
  v3Factory: string;
  positionManager: string;
  swapRouter: string;
  quoter: string;
  swapRouterCodeHash: string;
  quoterCodeHash: string;
  numeraire: NumeraireInfo;
  feeTier: number;
  launchpad: {
    implementation: string;
    pad: string;
    locker: string;
    implementationCodeHash: string;
    padCodeHash: string;
    lockerCodeHash: string;
    deploymentBlock: bigint;
  };
  role: ChainRole;
}

/** Canonical Uniswap V3 infra proven by DERIVING equality vs the configured row from the generated
 *  evidence's RAW facts (kami 24254 #2/#3) — never a summary boolean. */
function v3InfraProven(row: V3ChainRow, ev: V3ChainEvidence | undefined): boolean {
  const i = ev?.infra;
  return (
    !!i &&
    ev.chainId === row.id &&
    i.chainId === row.id &&
    i.numeraire.address.toLowerCase() === row.numeraire.address.toLowerCase() &&
    i.numeraire.decimals === row.numeraire.decimals &&
    i.numeraire.symbol === row.numeraire.symbol &&
    i.factory.address.toLowerCase() === row.v3Factory.toLowerCase() &&
    i.factory.feeTier === row.feeTier &&
    i.factory.tickSpacing > 0 &&
    i.factory.codeSize > 0 &&
    i.positionManager.address.toLowerCase() === row.positionManager.toLowerCase() &&
    i.positionManager.factoryBinding.toLowerCase() === row.v3Factory.toLowerCase() &&
    i.positionManager.codeSize > 0 &&
    !!i.verifiedAtBlock
  );
}

/** Hyde's OWN launchpad deployed + gojo's signed cross-bind/round-trip — the LAUNCH-enabled gate (kami #2).
 *  Canonical Uniswap infra alone is NOT enough: no deployed pad ⇒ not available. */
function v3LaunchProven(row: V3ChainRow, ev: V3ChainEvidence | undefined): boolean {
  const l = ev?.launch;
  const configured = row.launchpad;
  return (
    !!l &&
    isRealAddress(l.pad) &&
    isRealAddress(l.locker) &&
    !!l.implementation &&
    l.implementation.toLowerCase() === configured.implementation.toLowerCase() &&
    l.pad.toLowerCase() === configured.pad.toLowerCase() &&
    l.locker.toLowerCase() === configured.locker.toLowerCase() &&
    !!l.implementationCodeHash &&
    l.implementationCodeHash.toLowerCase() === configured.implementationCodeHash.toLowerCase() &&
    !!l.padCodeHash &&
    l.padCodeHash.toLowerCase() === configured.padCodeHash.toLowerCase() &&
    !!l.lockerCodeHash &&
    l.lockerCodeHash.toLowerCase() === configured.lockerCodeHash.toLowerCase() &&
    (l.implementationCodeSize ?? 0) > 0 &&
    l.padCodeSize > 0 &&
    l.lockerCodeSize > 0 &&
    // gojo's sign-off: cross-binding + deploy provenance + on-chain launch round-trip (~$5k FDV)
    !!l.padLockerBinding &&
    l.padLockerBinding.toLowerCase() === l.locker.toLowerCase() &&
    !!l.lockerFactoryBinding &&
    l.lockerFactoryBinding.toLowerCase() === l.pad.toLowerCase() &&
    isRealTxHash(l.deployTx) &&
    !!l.launchRoundTripFdv
  );
}

function positiveInteger(value?: string): boolean {
  try {
    return !!value && BigInt(value) > 0n;
  } catch {
    return false;
  }
}

/** Independent V3 trade release gate: both deployed runtime hashes, a real directional quote through
 * QuoterV2, and a successful funded exactInputSingle transaction to the configured SwapRouter02. */
function v3TradeProven(row: V3ChainRow, ev: V3ChainEvidence | undefined): boolean {
  const trade = ev?.trade;
  return (
    !!trade &&
    isRealAddress(row.swapRouter) &&
    isRealAddress(row.quoter) &&
    trade.swapRouter.toLowerCase() === row.swapRouter.toLowerCase() &&
    trade.quoter.toLowerCase() === row.quoter.toLowerCase() &&
    trade.swapRouterCodeHash?.toLowerCase() === row.swapRouterCodeHash.toLowerCase() &&
    trade.quoterCodeHash?.toLowerCase() === row.quoterCodeHash.toLowerCase() &&
    trade.quoteSmoke.tokenIn?.toLowerCase() === row.numeraire.address.toLowerCase() &&
    trade.quoteSmoke.fee === row.feeTier &&
    positiveInteger(trade.quoteSmoke.amountIn) &&
    positiveInteger(trade.quoteSmoke.amountOut) &&
    trade.quoteSmoke.routerAmountOut === trade.quoteSmoke.amountOut &&
    isRealAddress(trade.quoteSmoke.smokeAccount) &&
    !!trade.quoteSmoke.atBlock &&
    isRealTxHash(trade.tradeSmoke.txHash) &&
    !!trade.tradeSmoke.atBlock
  );
}

/** Derive a V3 chain's launch and trade capabilities independently. `ev` is injectable for tests;
 * defaults to the generated live-chain artifact. */
export function deriveV3Capability(
  row: V3ChainRow,
  ev: V3ChainEvidence | undefined = CHAIN_EVIDENCE_V3[row.id],
): ChainCapability {
  // Metadata must be real before 'live' (kami #3) — the row is source until gojo verifies the chain.
  const metadataReady = row.explorer.length > 0 && row.nativeSymbol.length > 0;
  const readSmoke = !!ev?.readSmoke && ev.chainId === row.id;
  // LIVE requires: canonical infra (derived vs row) AND Hyde deployed+signed AND metadata AND read smoke.
  const launchEnabled = v3InfraProven(row, ev) && v3LaunchProven(row, ev) && metadataReady && readSmoke;
  const tradeReady = launchEnabled && v3TradeProven(row, ev);
  const status: ChainStatus = launchEnabled ? "live" : "coming";
  return {
    id: row.id,
    name: row.name,
    shortName: row.shortName,
    logo: row.logo,
    nativeSymbol: row.nativeSymbol,
    explorer: row.explorer,
    status,
    role: tradeReady ? row.role : "launch",
    engine: "v3-single-sided",
    numeraire: row.numeraire,
    browse: { kind: "hyde-launches", markets: [] },
    trade: tradeReady
      ? {
          engine: "v3-single-sided",
          swapRouter: row.swapRouter,
          quoter: row.quoter,
          feeTier: row.feeTier,
          numeraire: row.numeraire,
        }
      : null,
    smoke: { read: readSmoke, trade: tradeReady },
    evidence: ev, // expose V3 evidence (kami #4) — no longer discarded
  };
}

/** V3-only chains (canonical Uniswap V3, no V4). Deployment addresses and runtime hashes are
 *  registry-pinned; live status still derives from generated on-chain evidence, never this row alone. */
export const V3_CANDIDATES: V3ChainRow[] = [
  {
    id: 5042,
    name: "Arc",
    shortName: "ARC",
    rpcUrl: "https://rpc.blockdaemon.mainnet.arc.io",
    explorer: "https://arc.exploreme.pro",
    nativeSymbol: "USDC",
    v3Factory: "0xf0db7b58379503491d857dB50AC9ece64c653918",
    positionManager: "0x39654A85A4C05127f5Fd6ED22CAeC077A0fB1377",
    swapRouter: "0x53bf6b0684ec7ef91e1387da3d1a1769bc5a6f77",
    quoter: "0x7dfd4f31be6814d2906bde155c3e1b146eac1468",
    swapRouterCodeHash: "0xc53680bc70e67f7e8818a0e1302e9b70a4460493bc6dd6db056575b17cb3af25",
    quoterCodeHash: "0xf222999269407743c526ee7c9d0c9b4fabec26773d48fd6fd257c5ebca976ea7",
    numeraire: {
      address: "0x3600000000000000000000000000000000000000",
      symbol: "USDC",
      decimals: 6,
      displayDecimals: 4,
      usdPegged: true,
    },
    feeTier: 10000,
    launchpad: {
      implementation: ZERO,
      pad: ZERO,
      locker: ZERO,
      implementationCodeHash: `0x${"0".repeat(64)}`,
      padCodeHash: `0x${"0".repeat(64)}`,
      lockerCodeHash: `0x${"0".repeat(64)}`,
      deploymentBlock: 0n,
    },
    role: "launch+trade",
  },
  {
    id: 988,
    name: "Stable",
    shortName: "STBL",
    rpcUrl: "https://rpc.stable.xyz",
    explorer: "https://stablescan.xyz", // verified (gojo 24328); matches the wagmi NetworkConfig
    nativeSymbol: "USDT0", // verified native gas symbol (gojo 24328) — NOT ETH; matches NetworkConfig
    v3Factory: "0x88F0a512eF09175D456bc9547f914f48C013E4aA",
    positionManager: "0x3BdC3437405f7D801b6036532713fc1F179136a6",
    swapRouter: "0x32eaf9B5d5F2CD7361c5012890C943D7de84C22a",
    quoter: "0xb070179E7032CdA868b53e6C1742F80c9e940d1A",
    swapRouterCodeHash: "0x058094ebcd628e76ed0308fd777ebbe4ece1005e2f1f53e3014f92f3e184277f",
    quoterCodeHash: "0x50e66edfe1f177d8b214cdbccc6de1828b3f1b360e517c2deb98b685e5cbb393",
    numeraire: {
      address: "0x779Ded0c9e1022225f8E0630b35a9b54bE713736",
      symbol: "USDT0",
      decimals: 6,
      displayDecimals: 4,
      usdPegged: true,
    },
    feeTier: 10000,
    launchpad: {
      implementation: "0xCA5C4C7cc97C9aA3ea56B5F3a5c50Eb1c086615b",
      pad: "0xE79F17Fe61F9c76824D74C496f122f0AB483ec6A",
      locker: "0xE43314319675eF26724a7d4381D95ac31c246d90",
      implementationCodeHash: "0xce745b5eba4a683f85e250477ced81eb3f04e5ba9a7ed705ef117e2acad6f012",
      padCodeHash: "0x26aa0599221e51251bb88b58d911f07905411f85690da2ea87fd0b505c5310dc",
      lockerCodeHash: "0xc45c37ee53500e275f9a166b07d3a44d5df088e6a0ca1a4af71c6c86b768c12e",
      deploymentBlock: 33271478n,
    },
    role: "launch+trade",
  },
  {
    id: 57073,
    name: "Ink",
    shortName: "INK",
    logo: "/chains/ink.svg",
    rpcUrl: "https://rpc-gel.inkonchain.com",
    explorer: "https://explorer.inkonchain.com",
    nativeSymbol: "ETH",
    v3Factory: "0x718E46d0962A66942E233760a8bd6038Ce54EdCD",
    positionManager: "0xefD0f78F93f578036AE34D52A813a4BE7D8D2D52",
    swapRouter: ZERO,
    quoter: ZERO,
    swapRouterCodeHash: `0x${"0".repeat(64)}`,
    quoterCodeHash: `0x${"0".repeat(64)}`,
    numeraire: {
      address: "0x4200000000000000000000000000000000000006",
      symbol: "WETH",
      decimals: 18,
      displayDecimals: 8,
      usdPegged: false,
    },
    feeTier: 3000,
    launchpad: {
      implementation: "0x83D7306e1d6B07a10AE070CD16e8F6320EFaDD98",
      pad: "0x71666A06bb454696073211733c755eA0194f3094",
      locker: "0x670697c84C5a18b28aA21D25888CcdCF2416be04",
      implementationCodeHash: "0x77499acdd5512646139cd69d341ce6bc0296ea5d0cd1da36fa6f1230b853a575",
      padCodeHash: "0x99695a2d251957778375390f46875593d6708250116040061e7d01244bb86cf7",
      lockerCodeHash: "0xccbd817a9025e9c26d38e3de752a04496738815a9fac5b070654e60f39423ebe",
      deploymentBlock: 53997401n,
    },
    role: "launch",
  },
];

export function v3ChainRow(chainId: number): V3ChainRow | undefined {
  return V3_CANDIDATES.find((row) => row.id === chainId);
}

// ------------------------------------------------------------ engine copy --
// The ONLY source of engine-specific launch copy. Components read ENGINE_META[capability.engine], so V4
// economics can never render on a V3 chain and vice-versa (kami 24242 copy gate). shiro owns the exact
// wording in her frame; the STRUCTURE — engine-keyed, no cross-engine string — is the guarantee.
export interface EngineMeta {
  title: string;
  subtitle: string;
  feeSplitLabel: string;
  trustLine: string;
  creatorShare: number;
  hydeShare: number;
  lockedLpShare: number;
}
export const ENGINE_META: Record<LaunchEngine, EngineMeta> = {
  "v3-single-sided": {
    title: "Uniswap V3 rail",
    subtitle: "Stablecoin settlement and permanent V3 custody.",
    feeSplitLabel: "95% creator • 5% Hyde", // kami 24242 — matches _split BPS exactly
    trustLine: "V3 positions are permanently locked; creator fees remain claimable.",
    creatorShare: 95,
    hydeShare: 5,
    lockedLpShare: 0,
  },
  "v4-hook": {
    title: "Uniswap V4 rail",
    subtitle: "Dynamic-fee hook and permanent V4 custody.",
    feeSplitLabel: "90% creator • 5% Hyde • 5% locked LP",
    trustLine: "V5 graduates into locked V4 positions; 5% of fees auto-compounds.",
    creatorShare: 90,
    hydeShare: 5,
    lockedLpShare: 5,
  },
};

/** Every candidate chain × engine (V4 + V3) with its derived (fail-closed) capability. A chain may appear
 *  more than once — one row per (chainId, engine) — so a chain can offer BOTH V3 and V4 (kami 24254 #1). */
export function chainCapabilities(): ChainCapability[] {
  return [
    ...CANDIDATES.map(({ net, shortName, role, logo }) => deriveCapability(net, shortName, role, logo)),
    ...V3_CANDIDATES.map((row) => deriveV3Capability(row)),
  ];
}

/** All engine capabilities for a chain (0, 1, or 2). Empty ⇒ the chain isn't in the registry. */
export function chainEngineCapabilities(
  chainId: number,
  caps: ChainCapability[] = chainCapabilities(),
): ChainCapability[] {
  return caps.filter((c) => c.id === chainId);
}

/** The capability for a specific (chainId, engine). Unknown pair ⇒ honestly 'unsupported' — the fail-closed
 *  answer the selector renders as a disabled engine button (e.g. V4 on a V3-only chain). */
export function chainEngineCapability(
  chainId: number,
  engine: LaunchEngine,
  caps: ChainCapability[] = chainCapabilities(),
): ChainCapability | { id: number; engine: LaunchEngine; status: "unsupported" } {
  return caps.find((c) => c.id === chainId && c.engine === engine) ?? { id: chainId, engine, status: "unsupported" };
}

/** Back-compat single-chain lookup — returns the FIRST engine's capability for a chain. Prefer the
 *  engine-aware lookups above when a specific engine matters (a chain can now expose more than one). */
export function chainCapability(chainId: number): ChainCapability | { id: number; status: "unsupported" } {
  const hit = chainEngineCapabilities(chainId)[0];
  return hit ?? { id: chainId, status: "unsupported" };
}

/** The launched chain's single-sided-V3 capability, if any — the ONLY fail-closed signal Stable-specific UI
 *  should use. It never matches a v4-hook chain (Robinhood), so it can't regress live V4 gates (kami 24334).
 *  Returns the V3 capability so callers can read its `status` (coming vs live). */
export function chainV3Capability(chainId: number): ChainCapability | undefined {
  return chainEngineCapabilities(chainId).find((c) => c.engine === "v3-single-sided");
}

/** Whether Hydeout can create launches on this chain today.
 *
 * V4 requires Hydeout's own deployed factory in addition to canonical Uniswap
 * infrastructure. V3 requires the generated deployment/binding evidence gate.
 * This is separate from `status`, whose in-app trade smoke gate is stricter
 * than launch readiness.
 */
export function isHydeLaunchLive(chainId: number, engine?: LaunchEngine): boolean {
  const capabilities = chainEngineCapabilities(chainId)
    .filter((capability) => !engine || capability.engine === engine)
    .filter((capability) => capability.role === "launch" || capability.role === "launch+trade");

  return capabilities.some((capability) => {
    if (capability.engine === "v3-single-sided") return capability.status === "live";
    return isRealAddress(V4_CONTRACTS_BY_CHAIN[chainId]?.hydeTokenFactory);
  });
}
